# Change 'comments' to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'touchstone-preschool'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: 'About', folder: 'documentation', file: 'welcome-to-millennial.html'}
- {name: 'Our Vision', folder: 'documentation', file: 'getting-started.html'}
- {name: 'Our Mission', folder: 'documentation', file: 'text-formatting.html'}
- {name: 'Curriculum', folder: 'documentation', file: 'learning-resources.html'}
- {name: 'Contact', folder: 'documentation', file: 'about-the-author.html'}
#- {name: 'Documentation', folder: 'pages', file: 'documentation.html'}


# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'facebook', link: 'https://www.facebook.com/TouchstonePreschool/'}
- {icon: 'instagram', link: 'https://instagram.com/touchstone.a.preschool'}
- {icon: 'envelope', link: 'mailto:touchstoneapreschool@gmail.com'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
#pagination:
  #next_page: 'Newer'
  #previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
